version: '3.1'

services:
    # Databases # #
    dataBaseGolang:
        image: postgres
        container_name: dataBaseGolang
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: user
        ports:
            - 25432:25432
            
    # API # #
    api:
        container_name: api-golang
        build: .
        ports:
            - 3003:3003
        volumes: 
            - .:/go/src/app    

    
